-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE ch01.restaurants_staging (
--   franchise text, lat double precision, lon double precision);
