insert into product (name, price) values ('Sugar - Brown, Individual', 874);
insert into product (name, price) values ('Zucchini - Green', 23);
insert into product (name, price) values ('Sour Cream', 788);
insert into product (name, price) values ('Capon - Breast, Wing On', 372);
insert into product (name, price) values ('Ice Cream - Super Sandwich', 166);
insert into product (name, price) values ('Pasta - Tortellini, Fresh', 412);
insert into product (name, price) values ('Squeeze Bottle', 889);
insert into product (name, price) values ('Ice Cream - Super Sandwich', 335);
insert into product (name, price) values ('Wine - Merlot Vina Carmen', 409);
insert into product (name, price) values ('Wine - Semi Dry Riesling Vineland', 210);
insert into product (name, price) values ('Pails With Lids', 677);
insert into product (name, price) values ('Bread Cranberry Foccacia', 552);
insert into product (name, price) values ('Port - 74 Brights', 767);
insert into product (name, price) values ('Chocolate - Compound Coating', 540);
insert into product (name, price) values ('Chilli Paste, Hot Sambal Oelek', 919);
insert into product (name, price) values ('Mix Pina Colada', 660);
insert into product (name, price) values ('Sage Ground Wiberg', 762);
insert into product (name, price) values ('Bar Special K', 986);
insert into product (name, price) values ('Icecream Cone - Areo Chocolate', 79);
insert into product (name, price) values ('Chocolate - Dark', 730);
insert into product (name, price) values ('Fennel - Seeds', 283);
insert into product (name, price) values ('Juice - Ocean Spray Kiwi', 300);
insert into product (name, price) values ('Eggplant - Baby', 795);
insert into product (name, price) values ('Chilli Paste, Sambal Oelek', 313);
insert into product (name, price) values ('Pork - Ham Hocks - Smoked', 933);
insert into product (name, price) values ('Wine - Masi Valpolocell', 413);
insert into product (name, price) values ('Soup - Campbells Chicken', 128);
insert into product (name, price) values ('Soup - Campbells', 173);
insert into product (name, price) values ('Snapple Raspberry Tea', 49);
insert into product (name, price) values ('Beer - Heinekin', 313);
insert into product (name, price) values ('Uniform Linen Charge', 849);
insert into product (name, price) values ('Split Peas - Green, Dry', 112);
insert into product (name, price) values ('Squash - Pepper', 933);
insert into product (name, price) values ('Wine - White, Gewurtzraminer', 333);
insert into product (name, price) values ('Black Currants', 84);
insert into product (name, price) values ('Oxtail - Cut', 939);
insert into product (name, price) values ('Soup - Campbells, Creamy', 265);
insert into product (name, price) values ('Wine - Winzer Krems Gruner', 298);
insert into product (name, price) values ('Butcher Twine 4r', 918);
insert into product (name, price) values ('Pork - Smoked Back Bacon', 621);
insert into product (name, price) values ('Shrimp - Black Tiger 26/30', 118);
insert into product (name, price) values ('Plastic Wrap', 374);
insert into product (name, price) values ('Wine - White, Ej', 959);
insert into product (name, price) values ('Rice Paper', 106);
insert into product (name, price) values ('Tomato - Peeled Italian Canned', 973);
insert into product (name, price) values ('Beer - True North Strong Ale', 730);
insert into product (name, price) values ('Cakes Assorted', 762);
insert into product (name, price) values ('Basil - Thai', 519);
insert into product (name, price) values ('Yogurt - Raspberry, 175 Gr', 505);
insert into product (name, price) values ('Kellogs Raisan Bran Bars', 473);
insert into product (name, price) values ('Wine - Red, Mouton Cadet', 49);
insert into product (name, price) values ('Beer - Sleeman Fine Porter', 360);
insert into product (name, price) values ('Oil - Macadamia', 331);
insert into product (name, price) values ('Longos - Lasagna Beef', 904);
insert into product (name, price) values ('Bacon Strip Precooked', 960);
insert into product (name, price) values ('Ice Cream Bar - Oreo Cone', 23);
insert into product (name, price) values ('Wine - Bouchard La Vignee Pinot', 987);
insert into product (name, price) values ('Wine - Pinot Noir Mondavi Coastal', 22);
insert into product (name, price) values ('Milk - 2% 250 Ml', 30);
insert into product (name, price) values ('Bread - Hamburger Buns', 442);
insert into product (name, price) values ('Appetizer - Asian Shrimp Roll', 53);
insert into product (name, price) values ('Assorted Desserts', 756);
insert into product (name, price) values ('Extract - Vanilla,artificial', 348);
insert into product (name, price) values ('Toothpick Frilled', 100);
insert into product (name, price) values ('Curry Paste - Madras', 206);
insert into product (name, price) values ('Chinese Foods - Thick Noodles', 902);
insert into product (name, price) values ('Doilies - 10, Paper', 890);
insert into product (name, price) values ('Steel Wool S.o.s', 292);
insert into product (name, price) values ('Pastry - Choclate Baked', 513);
insert into product (name, price) values ('Anisette - Mcguiness', 166);
insert into product (name, price) values ('Soup - Campbellschix Stew', 433);
insert into product (name, price) values ('Sauce - White, Mix', 274);
insert into product (name, price) values ('Assorted Desserts', 684);
insert into product (name, price) values ('Cake Circle, Foil, Scallop', 756);
insert into product (name, price) values ('Cheese - Swiss', 487);
insert into product (name, price) values ('Wine - George Duboeuf Rose', 279);
insert into product (name, price) values ('Pork - Back, Short Cut, Boneless', 132);
insert into product (name, price) values ('Syrup - Monin, Swiss Choclate', 490);
insert into product (name, price) values ('Syrup - Monin, Irish Cream', 578);
insert into product (name, price) values ('Beef - Salted', 425);
insert into product (name, price) values ('Broom - Corn', 571);
insert into product (name, price) values ('Juice - Apple, 1.36l', 434);
insert into product (name, price) values ('Chips - Assorted', 804);
insert into product (name, price) values ('Veal - Knuckle', 812);
insert into product (name, price) values ('Broom - Push', 339);
insert into product (name, price) values ('Ecolab Silver Fusion', 646);
insert into product (name, price) values ('Flavouring - Orange', 283);
insert into product (name, price) values ('Sauce - Ranch Dressing', 428);
insert into product (name, price) values ('Snails - Large Canned', 987);
insert into product (name, price) values ('Towels - Paper / Kraft', 172);
insert into product (name, price) values ('Lemonade - Kiwi, 591 Ml', 539);
insert into product (name, price) values ('Yogurt - Blueberry, 175 Gr', 82);
insert into product (name, price) values ('Napkin - Cocktail,beige 2 - Ply', 38);
insert into product (name, price) values ('Lamb - Leg, Boneless', 709);
insert into product (name, price) values ('Steel Wool S.o.s', 383);
insert into product (name, price) values ('Longos - Chicken Wings', 125);
insert into product (name, price) values ('Kellogs Special K Cereal', 624);
insert into product (name, price) values ('Muffin Mix - Carrot', 739);
insert into product (name, price) values ('Basil - Dry, Rubbed', 719);
insert into product (name, price) values ('Bread - Rolls, Corn', 159);
insert into product (name, price) values ('Flour - Whole Wheat', 308);
insert into product (name, price) values ('Munchies Honey Sweet Trail Mix', 813);
insert into product (name, price) values ('Bread Foccacia Whole', 797);
insert into product (name, price) values ('Sprouts - Onion', 960);
insert into product (name, price) values ('Soup - Campbells, Minestrone', 201);
insert into product (name, price) values ('Tart - Raisin And Pecan', 276);
insert into product (name, price) values ('Cinnamon - Ground', 487);
insert into product (name, price) values ('Beef - Cooked, Corned', 808);
insert into product (name, price) values ('Veal - Heart', 934);
insert into product (name, price) values ('Muffin Mix - Chocolate Chip', 532);
insert into product (name, price) values ('Bread - Rolls, Rye', 641);
insert into product (name, price) values ('Chinese Lemon Pork', 662);
insert into product (name, price) values ('Dc - Frozen Momji', 544);
insert into product (name, price) values ('Cocoa Powder - Natural', 161);
insert into product (name, price) values ('Chicken Breast Halal', 987);
insert into product (name, price) values ('Ice Cream - Life Savers', 869);
insert into product (name, price) values ('Mustard - Dijon', 846);
insert into product (name, price) values ('Wine - Alsace Gewurztraminer', 689);
insert into product (name, price) values ('Chocolate - Unsweetened', 608);
insert into product (name, price) values ('Turnip - Wax', 195);
insert into product (name, price) values ('Chocolate - Dark Callets', 610);
insert into product (name, price) values ('Mushroom - Chantrelle, Fresh', 766);
insert into product (name, price) values ('Tomatoes - Grape', 764);
insert into product (name, price) values ('Wine - Red, Concha Y Toro', 541);
insert into product (name, price) values ('Spinach - Spinach Leaf', 520);
insert into product (name, price) values ('Muffin - Zero Transfat', 994);
insert into product (name, price) values ('Venison - Liver', 89);
insert into product (name, price) values ('Wine - Chianti Classico Riserva', 714);
insert into product (name, price) values ('Bread - Granary Small Pull', 133);
insert into product (name, price) values ('Wine - Red, Lurton Merlot De', 693);
insert into product (name, price) values ('Wine - Red, Cabernet Sauvignon', 756);
insert into product (name, price) values ('Beets - Candy Cane, Organic', 695);
insert into product (name, price) values ('Plasticspoonblack', 335);
insert into product (name, price) values ('Onions - Red Pearl', 82);
insert into product (name, price) values ('Rabbit - Whole', 637);
insert into product (name, price) values ('Jam - Apricot', 105);
insert into product (name, price) values ('Cake Slab', 414);
insert into product (name, price) values ('Pepper - Sorrano', 20);
insert into product (name, price) values ('Pie Filling - Pumpkin', 712);
insert into product (name, price) values ('Pepper - Julienne, Frozen', 168);
insert into product (name, price) values ('Nut - Pecan, Pieces', 616);
insert into product (name, price) values ('Shichimi Togarashi Peppeers', 980);
insert into product (name, price) values ('Syrup - Chocolate', 426);
insert into product (name, price) values ('Wine - Merlot Vina Carmen', 210);
insert into product (name, price) values ('Muffin - Mix - Mango Sour Cherry', 856);
insert into product (name, price) values ('Mushroom - Morels, Dry', 604);
insert into product (name, price) values ('Quinoa', 600);
insert into product (name, price) values ('Muffin Batt - Blueberry Passion', 709);
insert into product (name, price) values ('Turnip - Mini', 962);
insert into product (name, price) values ('Eggroll', 803);
insert into product (name, price) values ('Table Cloth 72x144 White', 352);
insert into product (name, price) values ('Bacardi Breezer - Strawberry', 593);
insert into product (name, price) values ('Bread - Assorted Rolls', 930);
insert into product (name, price) values ('Gelatine Leaves - Bulk', 1);
insert into product (name, price) values ('Pepper - Chillies, Crushed', 246);
insert into product (name, price) values ('Cinnamon Buns Sticky', 121);
insert into product (name, price) values ('Beef - Short Loin', 457);
insert into product (name, price) values ('Quail - Jumbo Boneless', 755);
insert into product (name, price) values ('Sauce - Cranberry', 489);
insert into product (name, price) values ('Bread - Roll, Whole Wheat', 256);
insert into product (name, price) values ('Coffee - Hazelnut Cream', 158);
insert into product (name, price) values ('Onions Granulated', 883);
insert into product (name, price) values ('Apple - Northern Spy', 500);
insert into product (name, price) values ('Soup - Campbellschix Stew', 670);
insert into product (name, price) values ('Muffins - Assorted', 737);
insert into product (name, price) values ('Juice - Lemon', 596);
insert into product (name, price) values ('Mini - Vol Au Vents', 386);
insert into product (name, price) values ('Tea - Lemon Scented', 270);
insert into product (name, price) values ('Wine - German Riesling', 827);
insert into product (name, price) values ('Beef - Montreal Smoked Brisket', 229);
insert into product (name, price) values ('Curry Powder Madras', 54);
insert into product (name, price) values ('Wild Boar - Tenderloin', 572);
insert into product (name, price) values ('Wine - Red, Harrow Estates, Cab', 254);
insert into product (name, price) values ('Cheese - Mozzarella, Buffalo', 691);
insert into product (name, price) values ('Fond - Chocolate', 76);
insert into product (name, price) values ('White Fish - Filets', 839);
insert into product (name, price) values ('Everfresh Products', 966);
insert into product (name, price) values ('Wine - Jaboulet Cotes Du Rhone', 628);
insert into product (name, price) values ('Pepper - Chillies, Crushed', 177);
insert into product (name, price) values ('Salmon - Canned', 614);
insert into product (name, price) values ('Cheese - St. Paulin', 386);
insert into product (name, price) values ('Beer - Blue Light', 498);
insert into product (name, price) values ('Cup - 4oz Translucent', 108);
insert into product (name, price) values ('Lotus Rootlets - Canned', 386);
insert into product (name, price) values ('Beef - Ox Tongue, Pickled', 463);
insert into product (name, price) values ('Pastry - Baked Scones - Mini', 909);
insert into product (name, price) values ('Juice - Prune', 797);
insert into product (name, price) values ('Mushroom - Chantrelle, Fresh', 456);
insert into product (name, price) values ('Muffin - Mix - Bran And Maple 15l', 656);
insert into product (name, price) values ('Tart Shells - Savory, 4', 422);
insert into product (name, price) values ('Wine - Gewurztraminer Pierre', 951);
insert into product (name, price) values ('Tuna - Salad Premix', 965);
insert into product (name, price) values ('Clam Nectar', 66);
insert into product (name, price) values ('Wine - Charddonnay Errazuriz', 317);
insert into product (name, price) values ('Pasta - Orzo, Dry', 247);
insert into product (name, price) values ('Wine - White, Cooking', 992);
insert into product (name, price) values ('Cheese - Provolone', 523);
insert into product (name, price) values ('Pea - Snow', 850);
insert into product (name, price) values ('Fish - Scallops, Cold Smoked', 670);
insert into product (name, price) values ('Ecolab - Hobart Washarm End Cap', 721);
insert into product (name, price) values ('Truffle Shells - White Chocolate', 709);
insert into product (name, price) values ('Longos - Burritos', 41);
insert into product (name, price) values ('Rosemary - Primerba, Paste', 116);
insert into product (name, price) values ('Kiwi', 10);
insert into product (name, price) values ('Yokaline', 294);
insert into product (name, price) values ('Food Colouring - Pink', 536);
insert into product (name, price) values ('Bandage - Flexible Neon', 778);
insert into product (name, price) values ('Lamb - Shoulder, Boneless', 748);
insert into product (name, price) values ('Bar Mix - Lemon', 7);
insert into product (name, price) values ('Veal Inside - Provimi', 483);
insert into product (name, price) values ('Pie Shell - 9', 756);
insert into product (name, price) values ('Tofu - Soft', 932);
insert into product (name, price) values ('Turkey - Ground. Lean', 933);
insert into product (name, price) values ('Eggplant - Asian', 267);
insert into product (name, price) values ('Spice - Pepper Portions', 92);
insert into product (name, price) values ('Flour - All Purpose', 766);
insert into product (name, price) values ('Cookie Chocolate Chip With', 370);
insert into product (name, price) values ('Lamb - Shoulder', 172);
insert into product (name, price) values ('Trueblue - Blueberry 12x473ml', 712);
insert into product (name, price) values ('Flour - Whole Wheat', 579);
insert into product (name, price) values ('Cardamon Seed / Pod', 135);
insert into product (name, price) values ('Oil - Avocado', 3);
insert into product (name, price) values ('Beans - Fava Fresh', 957);
insert into product (name, price) values ('Dried Figs', 820);
insert into product (name, price) values ('Juice - Apple, 341 Ml', 552);
insert into product (name, price) values ('Sole - Iqf', 949);
insert into product (name, price) values ('Dc - Sakura Fu', 504);
insert into product (name, price) values ('Beer - Maudite', 298);
insert into product (name, price) values ('Wine - Chablis 2003 Champs', 771);
insert into product (name, price) values ('Butter - Pod', 410);
insert into product (name, price) values ('Pork - Smoked Back Bacon', 89);
insert into product (name, price) values ('Tea - Herbal - 6 Asst', 102);
insert into product (name, price) values ('Pasta - Penne, Rigate, Dry', 832);
insert into product (name, price) values ('Bread - Raisin Walnut Oval', 589);
insert into product (name, price) values ('Juice - Lime', 456);
insert into product (name, price) values ('Pears - Bosc', 222);
insert into product (name, price) values ('Napkin White', 439);
insert into product (name, price) values ('Ecolab - Medallion', 382);
insert into product (name, price) values ('Lamb - Leg, Bone In', 838);
insert into product (name, price) values ('Dill - Primerba, Paste', 155);
insert into product (name, price) values ('Bagelers - Cinn / Brown Sugar', 294);
insert into product (name, price) values ('Sesame Seed Black', 253);
insert into product (name, price) values ('Lid - 16 Oz And 32 Oz', 670);
insert into product (name, price) values ('Salmon Steak - Cohoe 8 Oz', 536);
insert into product (name, price) values ('Hipnotiq Liquor', 343);
insert into product (name, price) values ('Steampan - Half Size Shallow', 854);
insert into product (name, price) values ('Grapefruit - Pink', 423);
insert into product (name, price) values ('Wine - Red, Cabernet Merlot', 909);
insert into product (name, price) values ('Cake - Pancake', 443);
insert into product (name, price) values ('Bread Base - Toscano', 209);
insert into product (name, price) values ('Salmon - Smoked, Sliced', 518);
insert into product (name, price) values ('Bread - Pita', 42);
insert into product (name, price) values ('Crush - Orange, 355ml', 251);
insert into product (name, price) values ('Napkin - Beverge, White 2 - Ply', 251);
insert into product (name, price) values ('Pepper - Green, Chili', 525);
insert into product (name, price) values ('Transfer Sheets', 673);
insert into product (name, price) values ('Sauce - Chili', 885);
insert into product (name, price) values ('Chinese Foods - Chicken Wing', 289);
insert into product (name, price) values ('Banana - Green', 569);
insert into product (name, price) values ('Milk - Buttermilk', 740);
insert into product (name, price) values ('Wine - Lou Black Shiraz', 545);
insert into product (name, price) values ('The Pop Shoppe - Black Cherry', 177);
insert into product (name, price) values ('Juice - Tomato, 10 Oz', 765);
insert into product (name, price) values ('Squeeze Bottle', 612);
insert into product (name, price) values ('Beans - Green', 159);
insert into product (name, price) values ('Oil - Safflower', 781);
insert into product (name, price) values ('Browning Caramel Glace', 53);
insert into product (name, price) values ('Celery', 964);
insert into product (name, price) values ('Appetiser - Bought', 727);
insert into product (name, price) values ('Wine - Balbach Riverside', 278);
insert into product (name, price) values ('Sobe - Lizard Fuel', 415);
insert into product (name, price) values ('Allspice - Jamaican', 97);
insert into product (name, price) values ('Cleaner - Comet', 102);
insert into product (name, price) values ('Island Oasis - Strawberry', 866);
insert into product (name, price) values ('Uniform Linen Charge', 184);
insert into product (name, price) values ('Beans - Fine', 199);
insert into product (name, price) values ('Sausage - Meat', 306);
insert into product (name, price) values ('Wine - Hardys Bankside Shiraz', 235);
insert into product (name, price) values ('Corn Shoots', 250);
insert into product (name, price) values ('Yeast - Fresh, Fleischman', 799);
insert into product (name, price) values ('Flower - Daisies', 850);
insert into product (name, price) values ('Creme De Banane - Marie', 814);
insert into product (name, price) values ('Beef - Bones, Marrow', 631);
insert into product (name, price) values ('Snapple Lemon Tea', 822);
insert into product (name, price) values ('Beef - Inside Round', 706);
insert into product (name, price) values ('Mustard - Dijon', 613);
insert into product (name, price) values ('Lid Tray - 12in Dome', 183);
insert into product (name, price) values ('Spoon - Soup, Plastic', 364);
insert into product (name, price) values ('V8 - Tropical Blend', 120);
insert into product (name, price) values ('Gatorade - Xfactor Berry', 134);
insert into product (name, price) values ('Sesame Seed', 804);
insert into product (name, price) values ('Wine - Red, Black Opal Shiraz', 583);
insert into product (name, price) values ('Tea - Jasmin Green', 879);
insert into product (name, price) values ('Octopus', 163);
insert into product (name, price) values ('Nut - Pecan, Halves', 507);
insert into product (name, price) values ('Baking Powder', 449);
insert into product (name, price) values ('Veal - Chops, Split, Frenched', 562);
insert into product (name, price) values ('Cake Sheet Combo Party Pack', 543);
insert into product (name, price) values ('Glass Clear 8 Oz', 746);
insert into product (name, price) values ('Jello - Assorted', 305);
insert into product (name, price) values ('External Supplier', 842);
insert into product (name, price) values ('Lentils - Green Le Puy', 232);
insert into product (name, price) values ('Beef - Bones, Cut - Up', 910);
insert into product (name, price) values ('Garbag Bags - Black', 30);
insert into product (name, price) values ('Pastry - Trippleberry Muffin - Mini', 143);
insert into product (name, price) values ('Truffle Shells - White Chocolate', 626);
insert into product (name, price) values ('Garbag Bags - Black', 96);
insert into product (name, price) values ('Wine - Duboeuf Beaujolais', 921);
insert into product (name, price) values ('Cream - 18%', 288);
insert into product (name, price) values ('Pork - Back, Short Cut, Boneless', 287);
insert into product (name, price) values ('Lemonade - Black Cherry, 591 Ml', 33);
insert into product (name, price) values ('Parsley - Dried', 143);
insert into product (name, price) values ('Bread - Granary Small Pull', 882);
insert into product (name, price) values ('Juice - Propel Sport', 72);
insert into product (name, price) values ('Cabbage - Nappa', 565);
insert into product (name, price) values ('Coffee - Colombian, Portioned', 166);
insert into product (name, price) values ('Curry Paste - Green Masala', 239);
insert into product (name, price) values ('Bowl 12 Oz - Showcase 92012', 336);
insert into product (name, price) values ('Soup - Base Broth Beef', 8);
insert into product (name, price) values ('Bandage - Finger Cots', 331);
insert into product (name, price) values ('Crab Meat Claw Pasteurise', 852);
insert into product (name, price) values ('Beer - Heinekin', 201);
insert into product (name, price) values ('Pasta - Penne Primavera, Single', 670);
insert into product (name, price) values ('Crackers - Trio', 36);
insert into product (name, price) values ('Orange Roughy 4/6 Oz', 870);
insert into product (name, price) values ('Beer - Alexander Kieths, Pale Ale', 138);
insert into product (name, price) values ('Nut - Pumpkin Seeds', 670);
insert into product (name, price) values ('Pork - Butt, Boneless', 831);
insert into product (name, price) values ('Chicken - Soup Base', 87);
insert into product (name, price) values ('Loaf Pan - 2 Lb, Foil', 457);
insert into product (name, price) values ('Orange - Blood', 998);
insert into product (name, price) values ('Coffee Decaf Colombian', 216);
insert into product (name, price) values ('Numi - Assorted Teas', 851);
insert into product (name, price) values ('Bread - Mini Hamburger Bun', 833);
insert into product (name, price) values ('Bread - Dark Rye, Loaf', 725);
insert into product (name, price) values ('Cheese - Asiago', 843);
insert into product (name, price) values ('Samosa - Veg', 172);
insert into product (name, price) values ('Gelatine Powder', 79);
insert into product (name, price) values ('Oven Mitts - 15 Inch', 67);
insert into product (name, price) values ('Pastry - Lemon Danish - Mini', 929);
insert into product (name, price) values ('Beets - Candy Cane, Organic', 469);
insert into product (name, price) values ('Wine - Cotes Du Rhone Parallele', 332);
insert into product (name, price) values ('Beets - Mini Golden', 683);
insert into product (name, price) values ('Dasheen', 97);
insert into product (name, price) values ('Tomatoes - Roma', 456);
insert into product (name, price) values ('Wine - Magnotta - Pinot Gris Sr', 734);
insert into product (name, price) values ('Placemat - Scallop, White', 332);
insert into product (name, price) values ('Soup - Knorr, Classic Can. Chili', 461);
insert into product (name, price) values ('Apricots Fresh', 628);
insert into product (name, price) values ('Miso Paste White', 512);
insert into product (name, price) values ('Chocolate - White', 918);
insert into product (name, price) values ('Cabbage - Green', 467);
insert into product (name, price) values ('Pepper - Green, Chili', 186);
insert into product (name, price) values ('Flower - Potmums', 846);
insert into product (name, price) values ('Tomato - Tricolor Cherry', 903);
insert into product (name, price) values ('Cookies - Englishbay Wht', 895);
insert into product (name, price) values ('Compound - Orange', 629);
insert into product (name, price) values ('Pie Pecan', 21);
insert into product (name, price) values ('Butter - Salted', 106);
insert into product (name, price) values ('Hand Towel', 235);
insert into product (name, price) values ('Cattail Hearts', 222);
insert into product (name, price) values ('Wine - Beaujolais Villages', 697);
insert into product (name, price) values ('Ecolab - Hobart Washarm End Cap', 153);
insert into product (name, price) values ('Dehydrated Kelp Kombo', 305);
insert into product (name, price) values ('Pickerel - Fillets', 926);
insert into product (name, price) values ('Potatoes - Idaho 100 Count', 326);
insert into product (name, price) values ('Wine - Pinot Noir Pond Haddock', 869);
insert into product (name, price) values ('Beans - Fava Fresh', 402);
insert into product (name, price) values ('Sparkling Wine - Rose, Freixenet', 959);
insert into product (name, price) values ('Jameson - Irish Whiskey', 472);
insert into product (name, price) values ('Glycerine', 213);
insert into product (name, price) values ('Tarragon - Fresh', 199);
insert into product (name, price) values ('Container - Clear 16 Oz', 707);
insert into product (name, price) values ('Bread - Crumbs, Bulk', 381);
insert into product (name, price) values ('Miso Paste White', 389);
insert into product (name, price) values ('Kale - Red', 404);
insert into product (name, price) values ('Oil - Pumpkinseed', 460);
insert into product (name, price) values ('Rum - Mount Gay Eclipes', 313);
insert into product (name, price) values ('Cheese - Boursin, Garlic / Herbs', 458);
insert into product (name, price) values ('Wine - Red, Cooking', 963);
insert into product (name, price) values ('Mushroom - Porcini, Dry', 522);
insert into product (name, price) values ('Extract - Raspberry', 20);
insert into product (name, price) values ('Veal - Striploin', 262);
insert into product (name, price) values ('Sausage - Breakfast', 787);
insert into product (name, price) values ('Pails With Lids', 953);
insert into product (name, price) values ('Bread Base - Gold Formel', 999);
insert into product (name, price) values ('Transfer Sheets', 261);
insert into product (name, price) values ('Sugar - Crumb', 325);
insert into product (name, price) values ('Lambcasing', 182);
insert into product (name, price) values ('Soup - Campbells Beef Noodle', 932);
insert into product (name, price) values ('Wine - Zinfandel California 2002', 508);
insert into product (name, price) values ('Waffle Stix', 424);
insert into product (name, price) values ('Guinea Fowl', 339);
insert into product (name, price) values ('Wine - Casillero Deldiablo', 809);
insert into product (name, price) values ('Chickhen - Chicken Phyllo', 874);
insert into product (name, price) values ('Lychee - Canned', 342);
insert into product (name, price) values ('Jolt Cola - Red Eye', 31);
insert into product (name, price) values ('Mustard - Dijon', 659);
insert into product (name, price) values ('Longos - Assorted Sandwich', 737);
insert into product (name, price) values ('Vinegar - White', 115);
insert into product (name, price) values ('Chips - Miss Vickies', 723);
insert into product (name, price) values ('Nantucket Apple Juice', 795);
insert into product (name, price) values ('Puree - Guava', 776);
insert into product (name, price) values ('Milkettes - 2%', 465);
insert into product (name, price) values ('Broom - Corn', 428);
insert into product (name, price) values ('Bread Roll Foccacia', 489);
insert into product (name, price) values ('Onions - Vidalia', 528);
insert into product (name, price) values ('Muskox - French Rack', 549);
insert into product (name, price) values ('Pie Shells 10', 732);
insert into product (name, price) values ('Juice - V8 Splash', 40);
insert into product (name, price) values ('Jicama', 845);
insert into product (name, price) values ('Zucchini - Green', 572);
insert into product (name, price) values ('Longos - Lasagna Veg', 259);
insert into product (name, price) values ('Nut - Almond, Blanched, Whole', 869);
insert into product (name, price) values ('Cakes Assorted', 551);
insert into product (name, price) values ('Wine - Harrow Estates, Vidal', 116);
insert into product (name, price) values ('Veal - Eye Of Round', 322);
insert into product (name, price) values ('Jam - Marmalade, Orange', 590);
insert into product (name, price) values ('Irish Cream - Butterscotch', 358);
insert into product (name, price) values ('Salad Dressing', 177);
insert into product (name, price) values ('Wine - Charddonnay Errazuriz', 890);
insert into product (name, price) values ('Pork - Hock And Feet Attached', 304);
insert into product (name, price) values ('Loquat', 245);
insert into product (name, price) values ('Bread - Sour Sticks With Onion', 855);
insert into product (name, price) values ('Chef Hat 25cm', 981);
insert into product (name, price) values ('Truffle Cups - Brown', 518);
insert into product (name, price) values ('Cinnamon - Ground', 896);
insert into product (name, price) values ('Pineapple - Canned, Rings', 769);
insert into product (name, price) values ('Napkin White - Starched', 583);
insert into product (name, price) values ('Pork - Sausage Casing', 571);
insert into product (name, price) values ('Scallops - 10/20', 149);
insert into product (name, price) values ('Oil - Olive', 954);
insert into product (name, price) values ('Langers - Cranberry Cocktail', 969);
insert into product (name, price) values ('Soup - Campbells, Chix Gumbo', 765);
insert into product (name, price) values ('Anchovy Fillets', 409);
insert into product (name, price) values ('Pasta - Orzo, Dry', 626);
insert into product (name, price) values ('Wine - White, Mosel Gold', 763);
insert into product (name, price) values ('Dikon', 658);
insert into product (name, price) values ('Plate Pie Foil', 122);
insert into product (name, price) values ('Cookie Dough - Double', 977);
insert into product (name, price) values ('Sauce - Sesame Thai Dressing', 208);
insert into product (name, price) values ('Juice - Apple 284ml', 179);
insert into product (name, price) values ('Oil - Margarine', 309);
insert into product (name, price) values ('Island Oasis - Raspberry', 643);
insert into product (name, price) values ('Cheese - Taleggio D.o.p.', 159);
insert into product (name, price) values ('Mushroom - Chantrelle, Fresh', 258);
insert into product (name, price) values ('Pepsi - 600ml', 805);
insert into product (name, price) values ('Bouq All Italian - Primerba', 788);
insert into product (name, price) values ('Sausage - Blood Pudding', 550);
insert into product (name, price) values ('Corn Shoots', 777);
insert into product (name, price) values ('Wine - Beringer Founders Estate', 964);
insert into product (name, price) values ('Lid - 16 Oz And 32 Oz', 770);
insert into product (name, price) values ('Thyme - Dried', 988);
insert into product (name, price) values ('Lemon Pepper', 158);
insert into product (name, price) values ('Fond - Chocolate', 500);
insert into product (name, price) values ('Wine - Lou Black Shiraz', 857);
insert into product (name, price) values ('Tart Shells - Sweet, 2', 377);
insert into product (name, price) values ('Pasta - Detalini, White, Fresh', 651);
insert into product (name, price) values ('V8 Splash Strawberry Banana', 63);
insert into product (name, price) values ('Long Island Ice Tea', 946);
insert into product (name, price) values ('Stock - Beef, Brown', 136);
insert into product (name, price) values ('V8 - Berry Blend', 883);
insert into product (name, price) values ('Cookies - Amaretto', 126);
insert into product (name, price) values ('Tea - Herbal I Love Lemon', 680);
insert into product (name, price) values ('Broccoli - Fresh', 745);
insert into product (name, price) values ('Silicone Parch. 16.3x24.3', 64);
insert into product (name, price) values ('Duck - Whole', 63);
insert into product (name, price) values ('Syrup - Monin, Swiss Choclate', 11);
insert into product (name, price) values ('Crab - Dungeness, Whole, live', 936);
insert into product (name, price) values ('Pie Filling - Pumpkin', 584);
insert into product (name, price) values ('Pasta - Ravioli', 672);
insert into product (name, price) values ('Pears - Bosc', 983);
insert into product (name, price) values ('Parsnip', 858);
insert into product (name, price) values ('Liquid Aminios Acid - Braggs', 490);
insert into product (name, price) values ('Table Cloth 62x114 Colour', 461);
insert into product (name, price) values ('Snapple Raspberry Tea', 295);
insert into product (name, price) values ('Macaroons - Homestyle Two Bit', 896);
insert into product (name, price) values ('Pork - Inside', 813);
insert into product (name, price) values ('Rabbit - Legs', 604);
insert into product (name, price) values ('Pineapple - Regular', 693);
insert into product (name, price) values ('Wine - Casillero Del Diablo', 339);
insert into product (name, price) values ('Molasses - Fancy', 13);
insert into product (name, price) values ('Gherkin - Sour', 418);
insert into product (name, price) values ('Oil - Grapeseed Oil', 651);
insert into product (name, price) values ('Wine - Merlot Vina Carmen', 807);
insert into product (name, price) values ('Campari', 197);
insert into product (name, price) values ('Coconut - Creamed, Pure', 616);
insert into product (name, price) values ('Ginsing - Fresh', 772);
insert into product (name, price) values ('Wine - Redchard Merritt', 105);
insert into product (name, price) values ('Gelatine Leaves - Envelopes', 335);
insert into product (name, price) values ('Bread - Roll, Canadian Dinner', 623);
insert into product (name, price) values ('Hickory Smoke, Liquid', 437);
insert into product (name, price) values ('Soup - Verve - Chipotle Chicken', 234);
insert into product (name, price) values ('Beef - Kobe Striploin', 294);
insert into product (name, price) values ('Figs', 151);
insert into product (name, price) values ('Bread - Olive Dinner Roll', 704);
insert into product (name, price) values ('Sugar Thermometer', 234);
insert into product (name, price) values ('Bread Base - Gold Formel', 700);
insert into product (name, price) values ('External Supplier', 348);
insert into product (name, price) values ('Flour - Semolina', 374);
insert into product (name, price) values ('Tortillas - Flour, 8', 613);
insert into product (name, price) values ('Chocolate - Sugar Free Semi Choc', 7);
insert into product (name, price) values ('Pepper - Scotch Bonnet', 926);
insert into product (name, price) values ('Turkey - Breast, Bone - In', 326);
insert into product (name, price) values ('Beef Tenderloin Aaa', 528);
insert into product (name, price) values ('Sauce - Hoisin', 99);
insert into product (name, price) values ('Bamboo Shoots - Sliced', 339);
insert into product (name, price) values ('Asparagus - White, Fresh', 967);
insert into product (name, price) values ('Soup Campbells - Italian Wedding', 113);
insert into product (name, price) values ('Sage Ground Wiberg', 812);
insert into product (name, price) values ('Soup - Knorr, Classic Can. Chili', 115);
insert into product (name, price) values ('Cheese - Mascarpone', 521);
insert into product (name, price) values ('Wine - Zonnebloem Pinotage', 3);
insert into product (name, price) values ('Sauce - Rosee', 33);
insert into product (name, price) values ('Island Oasis - Mango Daiquiri', 393);
insert into product (name, price) values ('Club Soda - Schweppes, 355 Ml', 385);
insert into product (name, price) values ('Chicken - Livers', 281);
insert into product (name, price) values ('Chips - Miss Vickies', 988);
insert into product (name, price) values ('Asparagus - White, Canned', 520);
insert into product (name, price) values ('Wine - Saint Emilion Calvet', 265);
insert into product (name, price) values ('Yogurt - Peach, 175 Gr', 773);
insert into product (name, price) values ('White Baguette', 91);
insert into product (name, price) values ('Momiji Oroshi Chili Sauce', 663);
insert into product (name, price) values ('Rice - Basmati', 152);
insert into product (name, price) values ('Nantucket Apple Juice', 426);
insert into product (name, price) values ('Juice - Ocean Spray Cranberry', 490);
insert into product (name, price) values ('Lime Cordial - Roses', 344);
insert into product (name, price) values ('Muffin - Mix - Strawberry Rhubarb', 887);
insert into product (name, price) values ('Beef - Cooked, Corned', 364);
insert into product (name, price) values ('Wine - Red, Marechal Foch', 395);
insert into product (name, price) values ('Cheese - Feta', 25);
insert into product (name, price) values ('Icecream - Dstk Super Cone', 582);
insert into product (name, price) values ('Peppercorns - Green', 345);
insert into product (name, price) values ('Ocean Spray - Kiwi Strawberry', 46);
insert into product (name, price) values ('Pickle - Dill', 90);
insert into product (name, price) values ('Flax Seed', 690);
insert into product (name, price) values ('Bamboo Shoots - Sliced', 2);
insert into product (name, price) values ('Aspic - Clear', 177);
insert into product (name, price) values ('Energy Drink - Redbull 355ml', 474);
insert into product (name, price) values ('Bread - White, Unsliced', 230);
insert into product (name, price) values ('Apron', 649);
insert into product (name, price) values ('Pastry - Cheese Baked Scones', 913);
insert into product (name, price) values ('Pastry - Cherry Danish - Mini', 849);
insert into product (name, price) values ('Pie Filling - Apple', 333);
insert into product (name, price) values ('Miso Paste White', 941);
insert into product (name, price) values ('Jello - Assorted', 6);
insert into product (name, price) values ('Bread - Pullman, Sliced', 925);
insert into product (name, price) values ('Kale - Red', 290);
insert into product (name, price) values ('Rum - Coconut, Malibu', 641);
insert into product (name, price) values ('Brocolinni - Gaylan, Chinese', 97);
insert into product (name, price) values ('Bok Choy - Baby', 74);
insert into product (name, price) values ('Pastry - Cheese Baked Scones', 19);
insert into product (name, price) values ('Heavy Duty Dust Pan', 17);
insert into product (name, price) values ('Fiddlehead - Frozen', 646);
insert into product (name, price) values ('Pastrami', 520);
insert into product (name, price) values ('Tea - English Breakfast', 135);
insert into product (name, price) values ('Tea - Darjeeling, Azzura', 457);
insert into product (name, price) values ('Wine - Magnotta - Pinot Gris Sr', 439);
insert into product (name, price) values ('Yogurt - Banana, 175 Gr', 528);
insert into product (name, price) values ('Soup - Campbells, Chix Gumbo', 420);
insert into product (name, price) values ('Monkfish Fresh - Skin Off', 60);
insert into product (name, price) values ('Flour Dark Rye', 376);
insert into product (name, price) values ('Bread - Kimel Stick Poly', 444);
insert into product (name, price) values ('Wine - Barolo Fontanafredda', 763);
insert into product (name, price) values ('Tart Shells - Barquettes, Savory', 455);
insert into product (name, price) values ('Sugar - Icing', 527);
insert into product (name, price) values ('Dill Weed - Fresh', 79);
insert into product (name, price) values ('Sugar - Crumb', 811);
insert into product (name, price) values ('Cake - Pancake', 409);
insert into product (name, price) values ('Nut - Almond, Blanched, Sliced', 177);
insert into product (name, price) values ('Pepper - Red, Finger Hot', 374);
insert into product (name, price) values ('Oil - Margarine', 59);
insert into product (name, price) values ('Chips Potato Reg 43g', 377);
insert into product (name, price) values ('Milk - 2% 250 Ml', 3);
insert into product (name, price) values ('Hummus - Spread', 298);
insert into product (name, price) values ('Bread - Olive Dinner Roll', 849);
insert into product (name, price) values ('Soup - Chicken And Wild Rice', 225);
insert into product (name, price) values ('Calvados - Boulard', 472);
insert into product (name, price) values ('Chives - Fresh', 669);
insert into product (name, price) values ('Wine - Trimbach Pinot Blanc', 603);
insert into product (name, price) values ('Shiratamako - Rice Flour', 769);
insert into product (name, price) values ('Water - Aquafina Vitamin', 173);
insert into product (name, price) values ('Wine - Shiraz South Eastern', 703);
insert into product (name, price) values ('Bagel - Ched Chs Presliced', 142);
insert into product (name, price) values ('Wine - Casablanca Valley', 530);
insert into product (name, price) values ('Salt - Kosher', 112);
insert into product (name, price) values ('Shrimp - 150 - 250', 32);
insert into product (name, price) values ('Oil - Olive', 647);
insert into product (name, price) values ('Chocolate - White', 103);
insert into product (name, price) values ('Rum - Coconut, Malibu', 539);
insert into product (name, price) values ('Haggis', 437);
insert into product (name, price) values ('Bay Leaf', 613);
insert into product (name, price) values ('Appetizer - Southwestern', 681);
insert into product (name, price) values ('Chocolate Bar - Coffee Crisp', 812);
insert into product (name, price) values ('Whmis Spray Bottle Graduated', 68);
insert into product (name, price) values ('Wine - Barossa Valley Estate', 799);
insert into product (name, price) values ('Dc - Frozen Momji', 716);
insert into product (name, price) values ('Chips - Doritos', 56);
insert into product (name, price) values ('Chinese Foods - Plain Fried Rice', 126);
insert into product (name, price) values ('Doilies - 10, Paper', 808);
insert into product (name, price) values ('Icecream Bar - Del Monte', 549);
insert into product (name, price) values ('Coconut Milk - Unsweetened', 614);
insert into product (name, price) values ('Tequila Rose Cream Liquor', 294);
insert into product (name, price) values ('Shrimp - 16 - 20 Cooked, Peeled', 930);
insert into product (name, price) values ('Pasta - Agnolotti - Butternut', 547);
insert into product (name, price) values ('Tea - Decaf Lipton', 660);
insert into product (name, price) values ('Tuna - Salad Premix', 669);
insert into product (name, price) values ('Beef - Cooked, Corned', 983);
insert into product (name, price) values ('Sage Ground Wiberg', 903);
insert into product (name, price) values ('Chickensplit Half', 568);
insert into product (name, price) values ('Lettuce - Spring Mix', 468);
insert into product (name, price) values ('Bread - Flat Bread', 434);
insert into product (name, price) values ('Hog / Sausage Casing - Pork', 524);
insert into product (name, price) values ('Soup - Knorr, Chicken Noodle', 465);
insert into product (name, price) values ('Island Oasis - Peach Daiquiri', 199);
insert into product (name, price) values ('Mustard - Dry, Powder', 147);
insert into product (name, price) values ('Lemonade - Island Tea, 591 Ml', 494);
insert into product (name, price) values ('Rappini - Andy Boy', 630);
insert into product (name, price) values ('Bacon Strip Precooked', 71);
insert into product (name, price) values ('Wine - Beringer Founders Estate', 350);
insert into product (name, price) values ('Dried Figs', 278);
insert into product (name, price) values ('Ecolab Crystal Fusion', 647);
insert into product (name, price) values ('Ecolab Crystal Fusion', 565);
insert into product (name, price) values ('Flower - Carnations', 41);
insert into product (name, price) values ('Shrimp - Black Tiger 13/15', 39);
insert into product (name, price) values ('Juice - Grapefruit, 341 Ml', 897);
insert into product (name, price) values ('Sobe - Berry Energy', 639);
insert into product (name, price) values ('Buffalo - Short Rib Fresh', 446);
insert into product (name, price) values ('Ice Cream Bar - Oreo Cone', 760);
insert into product (name, price) values ('Pork - Tenderloin, Frozen', 162);
insert into product (name, price) values ('Gatorade - Orange', 723);
insert into product (name, price) values ('Ice Cream - Turtles Stick Bar', 161);
insert into product (name, price) values ('Soup - Campbells, Spinach Crm', 312);
insert into product (name, price) values ('Soup - Knorr, Veg / Beef', 848);
insert into product (name, price) values ('Star Fruit', 615);
insert into product (name, price) values ('Bar - Granola Trail Mix Fruit Nut', 459);
insert into product (name, price) values ('Cattail Hearts', 551);
insert into product (name, price) values ('Wine - Hardys Bankside Shiraz', 337);
insert into product (name, price) values ('Chocolate - Chips Compound', 669);
insert into product (name, price) values ('Red Pepper Paste', 649);
insert into product (name, price) values ('Tuna - Fresh', 802);
insert into product (name, price) values ('Dill Weed - Fresh', 253);
insert into product (name, price) values ('Hot Choc Vending', 646);
insert into product (name, price) values ('Trout Rainbow Whole', 426);
insert into product (name, price) values ('Pepper - Chili Powder', 666);
insert into product (name, price) values ('Gin - Gilbeys London, Dry', 59);
insert into product (name, price) values ('Roe - White Fish', 106);
insert into product (name, price) values ('Beans - Wax', 747);
insert into product (name, price) values ('Muffin Hinge Container 6', 177);
insert into product (name, price) values ('Eel - Smoked', 329);
insert into product (name, price) values ('Buffalo - Short Rib Fresh', 750);
insert into product (name, price) values ('Beans - Black Bean, Canned', 346);
insert into product (name, price) values ('Chives - Fresh', 257);
insert into product (name, price) values ('Soupfoamcont12oz 112con', 178);
insert into product (name, price) values ('Muffin Mix - Lemon Cranberry', 292);
insert into product (name, price) values ('Wine - Blue Nun Qualitatswein', 500);
insert into product (name, price) values ('Sambuca - Ramazzotti', 746);
insert into product (name, price) values ('Dill Weed - Dry', 233);
insert into product (name, price) values ('Celery Root', 993);
insert into product (name, price) values ('Wine - Red, Metus Rose', 764);
insert into product (name, price) values ('Laundry - Bag Cloth', 461);
insert into product (name, price) values ('Alize Gold Passion', 206);
insert into product (name, price) values ('Lid Coffee Cup 8oz Blk', 671);
insert into product (name, price) values ('Chicken Breast Halal', 906);
insert into product (name, price) values ('Brandy - Bar', 600);
insert into product (name, price) values ('Yokaline', 128);
insert into product (name, price) values ('Cape Capensis - Fillet', 248);
insert into product (name, price) values ('Wine - White, Colubia Cresh', 477);
insert into product (name, price) values ('Ecolab - Mikroklene 4/4 L', 486);
insert into product (name, price) values ('Wine - Fume Blanc Fetzer', 281);
insert into product (name, price) values ('Pasta - Fettuccine, Egg, Fresh', 981);
insert into product (name, price) values ('Soup - Campbells Beef Noodle', 629);
insert into product (name, price) values ('Muffin - Bran Ind Wrpd', 252);
insert into product (name, price) values ('Radish - Black, Winter, Organic', 272);
insert into product (name, price) values ('Tamarillo', 60);
insert into product (name, price) values ('Lamb - Whole, Fresh', 158);
insert into product (name, price) values ('Caviar - Salmon', 451);
insert into product (name, price) values ('Spinach - Spinach Leaf', 290);
insert into product (name, price) values ('Lobak', 82);
insert into product (name, price) values ('Wine - Winzer Krems Gruner', 99);
insert into product (name, price) values ('Eggplant - Baby', 735);
insert into product (name, price) values ('Durian Fruit', 917);
insert into product (name, price) values ('Wine - Cotes Du Rhone', 436);
insert into product (name, price) values ('Muffin Mix - Corn Harvest', 231);
insert into product (name, price) values ('Gloves - Goldtouch Disposable', 501);
insert into product (name, price) values ('Oil - Coconut', 722);
insert into product (name, price) values ('Grapefruit - Pink', 992);
insert into product (name, price) values ('Sauce - Alfredo', 621);
insert into product (name, price) values ('Truffle Shells - White Chocolate', 85);
insert into product (name, price) values ('Wine - Penfolds Koonuga Hill', 178);
insert into product (name, price) values ('Apples - Spartan', 459);
insert into product (name, price) values ('Bread - Corn Muffaletta', 939);
insert into product (name, price) values ('Beef - Tenderlion, Center Cut', 489);
insert into product (name, price) values ('Truffle - Whole Black Peeled', 310);
insert into product (name, price) values ('Coffee - Espresso', 904);
insert into product (name, price) values ('Milk 2% 500 Ml', 606);
insert into product (name, price) values ('Appetizer - Chicken Satay', 353);
insert into product (name, price) values ('Pasta - Spaghetti, Dry', 671);
insert into product (name, price) values ('Steel Wool', 24);
insert into product (name, price) values ('Beans - Navy, Dry', 889);
insert into product (name, price) values ('Chilli Paste, Sambal Oelek', 753);
insert into product (name, price) values ('Guinea Fowl', 512);
insert into product (name, price) values ('Vacuum Bags 12x16', 643);
insert into product (name, price) values ('Coffee - 10oz Cup 92961', 125);
insert into product (name, price) values ('Cheese - Ermite Bleu', 16);
insert into product (name, price) values ('Cheese - Le Cru Du Clocher', 781);
insert into product (name, price) values ('Beans - Black Bean, Dry', 960);
insert into product (name, price) values ('Pail - 15l White, With Handle', 444);
insert into product (name, price) values ('Squash - Pepper', 865);
insert into product (name, price) values ('Lid - Translucent, 3.5 And 6 Oz', 60);
insert into product (name, price) values ('Stock - Veal, White', 695);
insert into product (name, price) values ('Juice - Lemon', 917);
insert into product (name, price) values ('Amaretto', 799);
insert into product (name, price) values ('Munchies Honey Sweet Trail Mix', 754);
insert into product (name, price) values ('Sprouts - Baby Pea Tendrils', 544);
insert into product (name, price) values ('Pails With Lids', 6);
insert into product (name, price) values ('Veal - Shank, Pieces', 219);
insert into product (name, price) values ('Chocolate - Liqueur Cups With Foil', 498);
insert into product (name, price) values ('Coffee Cup 12oz 5342cd', 131);
insert into product (name, price) values ('Wine - Soave Folonari', 734);
insert into product (name, price) values ('Corn - Mini', 618);
insert into product (name, price) values ('Versatainer Nc - 9388', 907);
insert into product (name, price) values ('Bread - Roll, Whole Wheat', 182);
insert into product (name, price) values ('Onions - Red', 217);
insert into product (name, price) values ('Coffee Caramel Biscotti', 20);
insert into product (name, price) values ('Sauce - Mint', 652);
insert into product (name, price) values ('Vodka - Moskovskaya', 536);
insert into product (name, price) values ('Pasta - Fusili, Dry', 761);
insert into product (name, price) values ('Marjoram - Fresh', 14);
insert into product (name, price) values ('Breakfast Quesadillas', 306);
insert into product (name, price) values ('Star Fruit', 513);
insert into product (name, price) values ('Beans - Kidney, Canned', 191);
insert into product (name, price) values ('Star Fruit', 387);
insert into product (name, price) values ('Longos - Lasagna Veg', 78);
insert into product (name, price) values ('Spice - Chili Powder Mexican', 607);
insert into product (name, price) values ('Cookie - Oatmeal', 364);
insert into product (name, price) values ('Glaze - Clear', 877);
insert into product (name, price) values ('Chips - Potato Jalapeno', 307);
insert into product (name, price) values ('Container - Hngd Cll Blk 7x7x3', 662);
insert into product (name, price) values ('Bread - Crusty Italian Poly', 340);
insert into product (name, price) values ('Chocolate - Chips Compound', 28);
insert into product (name, price) values ('Bread - Kimel Stick Poly', 65);
insert into product (name, price) values ('Rye Special Old', 111);
insert into product (name, price) values ('Cake - Cake Sheet Macaroon', 467);
insert into product (name, price) values ('Tofu - Soft', 345);
insert into product (name, price) values ('Wine - Toasted Head', 812);
insert into product (name, price) values ('Chick Peas - Canned', 817);
insert into product (name, price) values ('Soup Campbells Beef With Veg', 354);
insert into product (name, price) values ('Asparagus - Frozen', 963);
insert into product (name, price) values ('Cumin - Whole', 547);
insert into product (name, price) values ('Melon - Watermelon Yellow', 350);
insert into product (name, price) values ('Towel Dispenser', 888);
insert into product (name, price) values ('Pepper - Black, Whole', 815);
insert into product (name, price) values ('Coconut Milk - Unsweetened', 303);
insert into product (name, price) values ('Venison - Striploin', 782);
insert into product (name, price) values ('Pumpkin - Seed', 456);
insert into product (name, price) values ('Tomato - Green', 248);
insert into product (name, price) values ('Lamb - Bones', 398);
insert into product (name, price) values ('Pepperoni Slices', 899);
insert into product (name, price) values ('Pork - Side Ribs', 852);
insert into product (name, price) values ('Soap - Pine Sol Floor Cleaner', 171);
insert into product (name, price) values ('Pepper - Scotch Bonnet', 887);
insert into product (name, price) values ('Yogurt - Peach, 175 Gr', 203);
insert into product (name, price) values ('Goldschalger', 753);
insert into product (name, price) values ('Lettuce - Boston Bib - Organic', 187);
insert into product (name, price) values ('Shiratamako - Rice Flour', 911);
insert into product (name, price) values ('Bacardi Breezer - Tropical', 766);
insert into product (name, price) values ('Puree - Blackcurrant', 225);
insert into product (name, price) values ('Peach - Halves', 124);
insert into product (name, price) values ('Sauce - Chili', 572);
insert into product (name, price) values ('Muffin - Mix - Mango Sour Cherry', 823);
insert into product (name, price) values ('Creme De Banane - Marie', 207);
insert into product (name, price) values ('Pasta - Detalini, White, Fresh', 695);
insert into product (name, price) values ('Sauce - Bernaise, Mix', 457);
insert into product (name, price) values ('Artichoke - Fresh', 588);
insert into product (name, price) values ('Curry Paste - Green Masala', 165);
insert into product (name, price) values ('Tea - Honey Green Tea', 246);
insert into product (name, price) values ('Green Tea Refresher', 300);
insert into product (name, price) values ('Wine - White, Colubia Cresh', 959);
insert into product (name, price) values ('Isomalt', 227);
insert into product (name, price) values ('Bay Leaf Fresh', 287);
insert into product (name, price) values ('Appetizer - Asian Shrimp Roll', 218);
insert into product (name, price) values ('Beef - Eye Of Round', 368);
insert into product (name, price) values ('Sachet', 113);
insert into product (name, price) values ('Orange - Blood', 569);
insert into product (name, price) values ('Amarula Cream', 44);
insert into product (name, price) values ('Coffee - Colombian, Portioned', 495);
insert into product (name, price) values ('Chick Peas - Canned', 355);
insert into product (name, price) values ('Cake - Night And Day Choclate', 320);
insert into product (name, price) values ('Beef - Bresaola', 91);
insert into product (name, price) values ('Lettuce - Lambs Mash', 368);
insert into product (name, price) values ('V8 - Tropical Blend', 391);
insert into product (name, price) values ('Beans - Turtle, Black, Dry', 498);
insert into product (name, price) values ('Capers - Ox Eye Daisy', 117);
insert into product (name, price) values ('Sansho Powder', 308);
insert into product (name, price) values ('Veal - Brisket, Provimi,bnls', 719);
insert into product (name, price) values ('Appetizer - Veg Assortment', 536);
insert into product (name, price) values ('Broom Handle', 359);
insert into product (name, price) values ('Onion Powder', 917);
insert into product (name, price) values ('Corn Meal', 769);
insert into product (name, price) values ('Beans - Black Bean, Dry', 909);
insert into product (name, price) values ('Hipnotiq Liquor', 685);
insert into product (name, price) values ('The Pop Shoppe - Black Cherry', 610);
insert into product (name, price) values ('Wine - Zonnebloem Pinotage', 501);
insert into product (name, price) values ('Sugar - Brown', 719);
insert into product (name, price) values ('Wine - Periguita Fonseca', 946);
insert into product (name, price) values ('Orange Roughy 4/6 Oz', 497);
insert into product (name, price) values ('Eggplant Italian', 272);
insert into product (name, price) values ('Puree - Blackcurrant', 814);
insert into product (name, price) values ('Wine - Red, Harrow Estates, Cab', 984);
insert into product (name, price) values ('Beef - Ground Medium', 896);
insert into product (name, price) values ('Wine - Trimbach Pinot Blanc', 328);
insert into product (name, price) values ('Beer - Sleemans Honey Brown', 766);
insert into product (name, price) values ('Peach - Fresh', 988);
insert into product (name, price) values ('Muffin - Mix - Strawberry Rhubarb', 274);
insert into product (name, price) values ('Soup - Campbells Beef Noodle', 209);
insert into product (name, price) values ('Potatoes - Instant, Mashed', 993);
insert into product (name, price) values ('Pastry - Banana Muffin - Mini', 216);
insert into product (name, price) values ('Petite Baguette', 586);
insert into product (name, price) values ('Chicken Breast Halal', 409);
insert into product (name, price) values ('Stock - Fish', 526);
insert into product (name, price) values ('Pastry - Baked Cinnamon Stick', 762);
insert into product (name, price) values ('Wine - Ice Wine', 947);
insert into product (name, price) values ('Nutmeg - Ground', 604);
insert into product (name, price) values ('Mustard Prepared', 915);
insert into product (name, price) values ('Crackers - Soda / Saltins', 138);
insert into product (name, price) values ('Rum - Cream, Amarula', 615);
insert into product (name, price) values ('Wine - Pinot Noir Pond Haddock', 381);
insert into product (name, price) values ('Bread - Rolls, Rye', 322);
insert into product (name, price) values ('Milk - Homo', 788);
insert into product (name, price) values ('Versatainer Nc - 8288', 527);
insert into product (name, price) values ('Tart Shells - Savory, 3', 747);
insert into product (name, price) values ('Spic And Span All Purpose', 592);
insert into product (name, price) values ('Corn Syrup', 761);
insert into product (name, price) values ('Chicken - Whole Fryers', 343);
insert into product (name, price) values ('Pepper - Green', 394);
insert into product (name, price) values ('Cheese - Taleggio D.o.p.', 581);
insert into product (name, price) values ('Lettuce - Red Leaf', 557);
insert into product (name, price) values ('Clam - Cherrystone', 564);
insert into product (name, price) values ('Crush - Cream Soda', 439);
insert into product (name, price) values ('Gelatine Powder', 174);
insert into product (name, price) values ('Lemon Balm - Fresh', 882);
insert into product (name, price) values ('Piping - Bags Quizna', 615);
insert into product (name, price) values ('Duck - Fat', 943);
insert into product (name, price) values ('Cream - 10%', 492);
insert into product (name, price) values ('Pepper - Black, Ground', 878);
insert into product (name, price) values ('Lettuce - Belgian Endive', 732);
insert into product (name, price) values ('Soup - Campbells', 58);
insert into product (name, price) values ('Plate Pie Foil', 925);
insert into product (name, price) values ('Sausage - Breakfast', 41);
insert into product (name, price) values ('Butcher Twine 4r', 514);
insert into product (name, price) values ('Chocolate - Sugar Free Semi Choc', 762);
insert into product (name, price) values ('Octopus - Baby, Cleaned', 910);
insert into product (name, price) values ('Juice - Orangina', 554);
insert into product (name, price) values ('Shrimp - Baby, Cold Water', 218);
insert into product (name, price) values ('Ice Cream - Fudge Bars', 275);
insert into product (name, price) values ('Tea - Black Currant', 446);
insert into product (name, price) values ('Cheese - Manchego, Spanish', 332);
insert into product (name, price) values ('Wine - Savigny - Les - Beaune', 872);
insert into product (name, price) values ('Jam - Strawberry, 20 Ml Jar', 714);
insert into product (name, price) values ('Soap - Mr.clean Floor Soap', 874);
insert into product (name, price) values ('Flour Dark Rye', 831);
insert into product (name, price) values ('Truffle Cups - White Paper', 716);
insert into product (name, price) values ('Sauce - Soya, Dark', 886);
insert into product (name, price) values ('Wine - George Duboeuf Rose', 77);
insert into product (name, price) values ('Longos - Burritos', 70);
insert into product (name, price) values ('Onions - Vidalia', 463);
insert into product (name, price) values ('Lamb - Leg, Bone In', 196);
insert into product (name, price) values ('Soup - Campbells, Lentil', 119);
insert into product (name, price) values ('Longos - Chicken Wings', 225);
insert into product (name, price) values ('Pickerel - Fillets', 325);
insert into product (name, price) values ('Cookie Dough - Double', 232);
insert into product (name, price) values ('Extract - Lemon', 201);
insert into product (name, price) values ('Sobe - Green Tea', 286);
insert into product (name, price) values ('Wine - Magnotta, Merlot Sr Vqa', 419);
insert into product (name, price) values ('Veal - Sweetbread', 737);
insert into product (name, price) values ('Huck Towels White', 488);
insert into product (name, price) values ('Tuna - Fresh', 579);
insert into product (name, price) values ('Island Oasis - Mango Daiquiri', 353);
insert into product (name, price) values ('Saskatoon Berries - Frozen', 701);
insert into product (name, price) values ('Glycerine', 998);
insert into product (name, price) values ('Eel Fresh', 415);
insert into product (name, price) values ('Tray - 16in Rnd Blk', 813);
insert into product (name, price) values ('Mushrooms - Honey', 118);
insert into product (name, price) values ('Bread - Roll, Whole Wheat', 147);
insert into product (name, price) values ('Bar Energy Chocchip', 138);
insert into product (name, price) values ('Island Oasis - Pina Colada', 321);
insert into product (name, price) values ('Table Cloth 81x81 White', 311);
insert into product (name, price) values ('Chestnuts - Whole,canned', 459);
insert into product (name, price) values ('Kolrabi', 158);
insert into product (name, price) values ('Lamb Leg - Bone - In Nz', 971);
insert into product (name, price) values ('Nut - Pecan, Pieces', 711);
insert into product (name, price) values ('Beef - Ground, Extra Lean, Fresh', 282);
insert into product (name, price) values ('Madeira', 91);
insert into product (name, price) values ('Bread - Mini Hamburger Bun', 606);
insert into product (name, price) values ('Parasol Pick Stir Stick', 83);
insert into product (name, price) values ('Nantucket - Kiwi Berry Cktl.', 576);
insert into product (name, price) values ('Wine - Red, Antinori Santa', 659);
insert into product (name, price) values ('Mussels - Cultivated', 308);
insert into product (name, price) values ('Water - Spring Water 500ml', 545);
insert into product (name, price) values ('Lemons', 765);
insert into product (name, price) values ('Lotus Root', 21);
insert into product (name, price) values ('Shrimp - 16/20, Iqf, Shell On', 668);
insert into product (name, price) values ('Wine - Chardonnay Mondavi', 573);
insert into product (name, price) values ('Cookie Choc', 797);
insert into product (name, price) values ('Muffin - Bran Ind Wrpd', 7);
insert into product (name, price) values ('Orange - Canned, Mandarin', 403);
insert into product (name, price) values ('Cherries - Maraschino,jar', 964);
insert into product (name, price) values ('Sping Loaded Cup Dispenser', 169);
insert into product (name, price) values ('Sunflower Seed Raw', 544);
insert into product (name, price) values ('Tea - Earl Grey', 855);
insert into product (name, price) values ('Broccoli - Fresh', 272);
insert into product (name, price) values ('Cheese - Comtomme', 541);
insert into product (name, price) values ('Soup - Verve - Chipotle Chicken', 44);
insert into product (name, price) values ('Pastry - Raisin Muffin - Mini', 388);
insert into product (name, price) values ('Appetizer - Chicken Satay', 785);
insert into product (name, price) values ('Pastry - Choclate Baked', 949);
insert into product (name, price) values ('Red Cod Fillets - 225g', 308);
insert into product (name, price) values ('Madeira', 525);
insert into product (name, price) values ('Pepper - Red, Finger Hot', 873);
insert into product (name, price) values ('Cheese - Augre Des Champs', 303);
insert into product (name, price) values ('Chocolate Bar - Oh Henry', 293);
insert into product (name, price) values ('Bread - Italian Roll With Herbs', 952);
insert into product (name, price) values ('Coconut - Creamed, Pure', 668);
insert into product (name, price) values ('Tortillas - Flour, 12', 132);
insert into product (name, price) values ('Ham - Procutinni', 373);
insert into product (name, price) values ('Juice - Lagoon Mango', 507);
insert into product (name, price) values ('Bananas', 120);
insert into product (name, price) values ('Plate - Foam, Bread And Butter', 992);
insert into product (name, price) values ('Skewers - Bamboo', 202);
insert into product (name, price) values ('Wine - Pinot Noir Stoneleigh', 513);
insert into product (name, price) values ('Beef - Inside Round', 130);
insert into product (name, price) values ('Beets - Pickled', 659);
insert into product (name, price) values ('Chicken - Livers', 144);
insert into product (name, price) values ('Tomato Puree', 393);
insert into product (name, price) values ('Appetizer - Lobster Phyllo Roll', 637);
insert into product (name, price) values ('Berry Brulee', 308);
insert into product (name, price) values ('Muffins - Assorted', 398);
insert into product (name, price) values ('Wine - Coteaux Du Tricastin Ac', 461);
insert into product (name, price) values ('Flour - Cake', 302);
insert into product (name, price) values ('Butter Balls Salted', 330);
insert into product (name, price) values ('Pate - Liver', 757);
insert into product (name, price) values ('Flower - Daisies', 72);
insert into product (name, price) values ('Wine - Red, Cabernet Sauvignon', 707);
insert into product (name, price) values ('Olives - Black, Pitted', 992);
insert into product (name, price) values ('Pimento - Canned', 307);
insert into product (name, price) values ('Oil - Sunflower', 290);
insert into product (name, price) values ('Creme De Cacao Mcguines', 655);
insert into product (name, price) values ('C - Plus, Orange', 398);
insert into product (name, price) values ('Muffin Mix - Corn Harvest', 793);
insert into product (name, price) values ('Soup - Campbells - Tomato', 140);
insert into product (name, price) values ('Wonton Wrappers', 448);
insert into product (name, price) values ('French Kiss Vanilla', 507);
insert into product (name, price) values ('Ecolab - Hobart Upr Prewash Arm', 319);
insert into product (name, price) values ('Coffee - Beans, Whole', 189);
insert into product (name, price) values ('Zucchini - Mini, Green', 843);
insert into product (name, price) values ('Beef - Diced', 262);
insert into product (name, price) values ('Puree - Passion Fruit', 571);
insert into product (name, price) values ('Ecolab Digiclean Mild Fm', 963);
insert into product (name, price) values ('Goat - Leg', 679);
insert into product (name, price) values ('Ecolab - Power Fusion', 64);
insert into product (name, price) values ('Muffin Mix - Raisin Bran', 469);
insert into product (name, price) values ('Bamboo Shoots - Sliced', 919);
insert into product (name, price) values ('Sauce Tomato Pouch', 399);
insert into product (name, price) values ('Corn - On The Cob', 284);
insert into product (name, price) values ('Cleaner - Pine Sol', 941);
insert into product (name, price) values ('Beef - Ox Tongue', 37);
insert into product (name, price) values ('Tea - Herbal I Love Lemon', 854);
insert into product (name, price) values ('Clams - Bay', 996);
insert into product (name, price) values ('Vinegar - Rice', 475);
insert into product (name, price) values ('Crackers Cheez It', 991);
insert into product (name, price) values ('Flavouring Vanilla Artificial', 822);
insert into product (name, price) values ('Wine - Periguita Fonseca', 434);
insert into product (name, price) values ('Cheese Cloth', 297);
insert into product (name, price) values ('Table Cloth 91x91 Colour', 327);
insert into product (name, price) values ('Pop - Club Soda Can', 426);
insert into product (name, price) values ('Napkin White', 113);
insert into product (name, price) values ('Chocolate - Liqueur Cups With Foil', 631);
insert into product (name, price) values ('Table Cloth - 53x69 Colour', 775);
insert into product (name, price) values ('Soup - Campbells - Chicken Noodle', 421);
insert into product (name, price) values ('Kolrabi', 638);
insert into product (name, price) values ('Magnotta Bel Paese Red', 498);
insert into product (name, price) values ('Energy Drink Bawls', 794);
insert into product (name, price) values ('Turkey Tenderloin Frozen', 274);
insert into product (name, price) values ('Glove - Cutting', 127);
insert into product (name, price) values ('Sprite, Diet - 355ml', 708);
insert into product (name, price) values ('Fish - Soup Base, Bouillon', 915);
insert into product (name, price) values ('Coffee Swiss Choc Almond', 8);
insert into product (name, price) values ('Beer - Sleemans Cream Ale', 410);
insert into product (name, price) values ('Oil - Sunflower', 944);
insert into product (name, price) values ('Pasta - Cappellini, Dry', 375);
insert into product (name, price) values ('Pork - Backfat', 428);
insert into product (name, price) values ('Gherkin', 678);
insert into product (name, price) values ('Lemonade - Strawberry, 591 Ml', 75);
insert into product (name, price) values ('Ecolab - Ster Bac', 227);
insert into product (name, price) values ('Plastic Wrap', 71);
insert into product (name, price) values ('Arizona - Green Tea', 377);
insert into product (name, price) values ('Wine - Prosecco Valdobienne', 220);
insert into product (name, price) values ('Sproutsmustard Cress', 771);
insert into product (name, price) values ('Spinach - Baby', 740);
