-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into permission (name) values
-- ('view_all_timesheets'),
-- ('edit_all_timesheets'),
-- ('edit_assigned_projects'),
-- ('delete_assigned_projects'),
-- ('view_money_gantt_on_assigned_projects'),
-- ('view_all_projects'),
-- ('edit_all_projects');
