-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE books (
--   id              INT           NOT NULL    IDENTITY    PRIMARY KEY,
--   title           VARCHAR(100)  NOT NULL,
--   primary_author  VARCHAR(100),
-- );
