-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create table if not exists region (
--   value text primary key,
--   description text);
