-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE ch01.lu_franchises (id char(3) PRIMARY KEY
--  , franchise varchar(30));
--
-- INSERT INTO ch01.lu_franchises(id, franchise)
-- VALUES
--   ('BKG', 'Burger King'), ('CJR', 'Carl''s Jr'),
--   ('HDE', 'Hardee'), ('INO', 'In-N-Out'),
--   ('JIB', 'Jack in the Box'), ('KFC', 'Kentucky Fried Chicken'),
--   ('MCD', 'McDonald'), ('PZH', 'Pizza Hut'),
--   ('TCB', 'Taco Bell'), ('WDY', 'Wendys');
