-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create materialized view if not exists asset_with_traits as
--   select
--     *
--     from
--       asset_denormed;
