FROM node:lts
WORKDIR /root

RUN npm i @graphql-mesh/cli graphql
RUN npm i @graphql-mesh/graphql
RUN npm i @graphql-mesh/grpc
RUN npm i @graphql-mesh/json-schema
RUN npm i @graphql-mesh/merger-federation
RUN npm i @graphql-mesh/mongoose
RUN npm i @graphql-mesh/mysql
RUN npm i @graphql-mesh/neo4j
RUN npm i @graphql-mesh/odata
RUN npm i @graphql-mesh/openapi
RUN npm i @graphql-mesh/postgraphile
RUN npm i @graphql-mesh/soap
RUN npm i @graphql-mesh/thrift
RUN npm i @graphql-mesh/transform-cache
RUN npm i @graphql-mesh/transform-federation
RUN npm i @graphql-mesh/transform-federation
RUN npm i @graphql-mesh/transform-filter-schema
RUN npm i @graphql-mesh/transform-mock
RUN npm i @graphql-mesh/transform-naming-convention
RUN npm i @graphql-mesh/transform-prefix
RUN npm i @graphql-mesh/transform-rename
RUN npm i @graphql-mesh/transform-rename
RUN npm i @graphql-mesh/transform-resolvers-composition
RUN npm i @graphql-mesh/transform-snapshot
RUN npm i @graphql-mesh/tuql

CMD npx mesh dev
