initdb.d-postgres/servers.jsonl:
	curl -s -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" "http://localhost:4011/compute-ops/v1beta2/servers?[1-100]" | jq -cr '.items[]' > $@

initdb.d-postgres/alerts.jsonl:
	curl -s -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" "http://localhost:4011/compute-ops/v1beta2/servers/177751-Y66%252B8899177751666258/alerts?[1-100]" | jq -cr '.items[]' > $@

