insert into PROJECT (name) values ('Guerza');
insert into PROJECT (name) values ('Australian sea lion');
insert into PROJECT (name) values ('Python (unidentified)');
insert into PROJECT (name) values ('Comb duck');
insert into PROJECT (name) values ('Indian porcupine');
insert into PROJECT (name) values ('Cormorant, large');
insert into PROJECT (name) values ('Meerkat');
insert into PROJECT (name) values ('Silver-backed jackal');
insert into PROJECT (name) values ('Dove, little brown');
insert into PROJECT (name) values ('Gray heron');
insert into PROJECT (name) values ('Blue fox');
insert into PROJECT (name) values ('Savannah deer (unidentified)');
insert into PROJECT (name) values ('Mouse, four-striped grass');
insert into PROJECT (name) values ('Owl, white-browed');
insert into PROJECT (name) values ('Javanese cormorant');
insert into PROJECT (name) values ('Heron, yellow-crowned night');
insert into PROJECT (name) values ('Red-billed tropic bird');
insert into PROJECT (name) values ('Striped hyena');
insert into PROJECT (name) values ('Roan antelope');
insert into PROJECT (name) values ('Bear, polar');
