-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create index if not exists leaderboard_snapshot_idx on leaderboard_snapshot (rank, id);
