-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into region (value, description)
-- values
--   ('NORTHEAST', 'New England'),
--   ('MIDWEST', 'Great Lakes'),
--   ('SOUTH', 'Dixie'),
--   ('PLAINS', 'Great Plains'),
--   ('APPALACHIA', 'Pennsylvania and West Virginia'),
--   ('MOUNTAIN', 'Rocky Mountains'),
--   ('NORTHWEST', 'Rainy'),
--   ('WEST', 'California'),
--   ('SOUTHWEST', 'Cacti');
