-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create materialized view if not exists snowflake_account_summary_cached as
--   select * from snowflake_account_summary;
