-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table assignment enable row level security;
--
-- alter table assignment force row level security;
--
-- alter table organization enable row level security;
--
-- alter table organization force row level security;
--
-- alter table permission enable row level security;
--
-- alter table permission force row level security;
--
-- alter table project enable row level security;
--
-- alter table project force row level security;
--
-- alter table timesheet enable row level security;
--
-- alter table timesheet force row level security;
--
-- alter table "user" enable row level security;
--
-- alter table "user" force row level security;
--
-- alter table user_permission enable row level security;
--
-- alter table user_permission force row level security;
