-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into product_category (name) values ('Purple');
-- insert into product_category (name) values ('Red');
-- insert into product_category (name) values ('Indigo');
-- insert into product_category (name) values ('Green');
-- insert into product_category (name) values ('Violet');
-- insert into product_category (name) values ('Pink');
-- insert into product_category (name) values ('Crimson');
-- insert into product_category (name) values ('Orange');
-- insert into product_category (name) values ('Khaki');
-- insert into product_category (name) values ('Orange');
