-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create materialized view if not exists leaderboard_snapshot as
--   select
--     *
--     from
--       leaderboard;
