-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create policy query on assignment for select using (true);
--
-- create policy query on organization for select using (true);
--
-- create policy query on permission for select using (true);
--
-- create policy query on project for select using (true);
--
-- create policy query on timesheet for select using (true);
--
-- create policy query on "user" for select using (true);
--
-- create policy query on user_permission for select using (true);
