-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create server origin foreign data wrapper postgres_fdw options (host 'origin', dbname 'postgres', port '5432');
