create table if not exists misc (
  bigint_field bigint,
  bigserial_field bigserial,
  bit_field bit(8),
  bit_varying_field bit varying(8),
  boolean_field boolean,
  box_field box,
  bytea_field bytea,
  character_field character(8),
  character_varying_field character varying(8),
  cidr_field cidr,
  circle_field circle,
  date_field date,
  double_precision_field double precision,
  inet_field inet,
  integer_field integer,
  interval_field interval,
  json_field json,
  jsonb_field jsonb,
  line_field line,
  lseg_field lseg,
  -- ltree_field ltree,
  -- geometry_field geometry,
  -- geography_field geography,
  macaddr_field macaddr,
  macaddr8_field macaddr8,
  money_field money,
  numeric_field numeric(10, 3),
  path_field path,
  pg_lsn_field pg_lsn,
  point_field point,
  polygon_field polygon,
  real_field real,
  smallint_field smallint,
  smallserial_field smallserial,
  serial_field serial,
  text_field text,
  time_without_time_zone_field time without time zone,
  time_with_time_zone_field time with time zone,
  timestamp_without_time_zone_field timestamp without time zone,
  timestamp_with_time_zone_field timestamp with time zone,
  tsquery_field tsquery,
  tsvector_field tsvector,
  txid_snapshot_field txid_snapshot,
  uuid_field uuid,
  xml_field xml
);
