FROM postgres:15
RUN apt-get update -y
RUN apt-get install postgresql-contrib -y
RUN apt-get install faker -y
RUN apt-get install python -y
RUN apt-get install pip -y
RUN apt-get install parallel -y
RUN apt-get install jq -y
