-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table account enable row level security;
--
-- alter table account force row level security;
--
-- alter table "order" enable row level security;
--
-- alter table "order" force row level security;
--
-- alter table order_detail enable row level security;
--
-- alter table order_detail force row level security;
